CREATE LOGIN ExternalLogin WITH PASSWORD='ChatAppPassword123';

CREATE DATABASE ChatApp
GO
USE ChatApp
GO

CREATE USER [ExternalUser] FOR LOGIN [ExternalLogin] WITH DEFAULT SCHEMA [dbo]
EXEC sp_addrolemember 'db_datareader', 'ExternalUser'
EXEC sp_addrolemember 'db_datawriter', 'ExternalUser'


GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AktivniKorisnici](
	[KonekcijaId] [nvarchar](450) NOT NULL,
	[KorisnickoIme] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_AktivniKorisnici] PRIMARY KEY CLUSTERED 
(
	[KonekcijaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Poruke](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OdKorisnika] [nvarchar](max) NOT NULL,
	[Sadrzaj] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Poruke] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
